import {catalog,t,language,setLanguage,languages,translateStatic,number,errorText} from './i18n.js';
import {rankItems} from './lib/relevance.mjs';
import {sources} from './lib/sources.mjs';
import {classify,mergeItems,inQuietHours,safeUrl,validItem,type Item} from './core.js';
type SourceState={items:Item[],checkedAt:string,error?:string};
type Reminder={id:string,name:string,at:string,notified:boolean};
type State={version:1,theme:string,disabled:string[],read:string[],saved:Item[],manual:Item[],alerts:boolean,quietStart:number,quietEnd:number,cap:number,seen:string[],day:string,sent:number,reminders:Reminder[]};
const $=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
const defaults=():State=>({version:1,theme:globalThis.matchMedia?.('(prefers-color-scheme: light)').matches?'light':'dark',disabled:[],read:[],saved:[],manual:[],alerts:false,quietStart:22,quietEnd:8,cap:5,seen:[],day:'',sent:0,reminders:[]});
let state=defaults(),cache:Record<string,SourceState>={},view='all',query='',unread=false,limit=25,busy=false,initialized=false;
function parseState(raw:any):State{if(!raw||raw.version!==1)throw Error(t("Choose a Khonrelay backup."));const s=defaults();for(const key of ['saved','manual'] as const)s[key]=Array.isArray(raw[key])?raw[key].filter(validItem).slice(0,500):[];for(const key of ['disabled','read','seen'] as const)s[key]=Array.isArray(raw[key])?raw[key].filter((x:unknown)=>typeof x==='string').slice(-3000):[];s.theme=raw.theme==='dark'||raw.theme==='light'?raw.theme:s.theme;s.alerts=raw.alerts===true;s.quietStart=Number.isInteger(raw.quietStart)&&raw.quietStart>=0&&raw.quietStart<24?raw.quietStart:22;s.quietEnd=Number.isInteger(raw.quietEnd)&&raw.quietEnd>=0&&raw.quietEnd<24?raw.quietEnd:8;s.cap=[3,5,10].includes(raw.cap)?raw.cap:5;s.reminders=Array.isArray(raw.reminders)?raw.reminders.filter((r:any)=>r&&typeof r.id==='string'&&typeof r.name==='string'&&r.name.length<=80&&typeof r.at==='string'&&Number.isFinite(Date.parse(r.at))).slice(0,20).map((r:any)=>({...r,notified:r.notified===true})):[];s.day=typeof raw.day==='string'?raw.day:'';s.sent=Number.isInteger(raw.sent)?Math.max(0,Math.min(10,raw.sent)):0;return s;}
try{const raw=localStorage.getItem('quiet-signal-v1');if(raw)state=parseState(JSON.parse(raw));const c=JSON.parse(localStorage.getItem('quiet-signal-cache')||'{}');for(const s of sources)if(c[s.id]&&Array.isArray(c[s.id].items))cache[s.id]={items:c[s.id].items.filter(validItem).slice(0,40),checkedAt:c[s.id].checkedAt,error:c[s.id].error};}catch{$('notice').textContent=t("Could not restore local data. You can import a backup in Preferences.");}
function save(){try{state.read=state.read.slice(-3000);state.seen=state.seen.slice(-3000);localStorage.setItem('quiet-signal-v1',JSON.stringify(state));localStorage.setItem('quiet-signal-cache',JSON.stringify(cache));}catch{$('notice').textContent=t("Browser storage is unavailable or full. Export a backup in Preferences.");}}
function el<K extends keyof HTMLElementTagNameMap>(tag:K,text='',cls=''){const n=document.createElement(tag);n.textContent=text;n.className=cls;return n;}
function button(text:string,fn:()=>void){const b=el('button',text);b.type='button';b.addEventListener('click',fn);return b;}
function link(text:string,url:string){const a=el('a',text);a.href=safeUrl(url)||'#';a.target='_blank';a.rel='noopener noreferrer';return a;}
function all(){return mergeItems([...sources.filter(s=>!state.disabled.includes(s.id)).flatMap(s=>cache[s.id]?.items||[]),...state.manual]);}
let relevanceSnapshot:unknown=null,relevanceEnabled=false;
function selected():Item[]{let items=view==='saved'?state.saved:all();if(view==='important')items=items.filter(i=>classify(i).important&&i.sourceId!=='manual');if(view==='release'||view==='reset'||view==='incident')items=items.filter(i=>classify(i).category===view);const filtered=mergeItems(items).filter(i=>(!unread||!state.read.includes(i.id))&&(!query||(i.title+' '+i.summary+' '+i.sourceName).toLowerCase().includes(query.toLowerCase())));return relevanceEnabled?rankItems(filtered,relevanceSnapshot):filtered;}
function formatDate(d:string|null){return d&&Number.isFinite(Date.parse(d))?new Intl.DateTimeFormat(language,{month:'short',day:'numeric',year:'numeric'}).format(new Date(d)):t("Date not supplied");}
const views=[["all", "All updates"], ["important", "Important"], ["release", "Releases"], ["reset", "Reset news"], ["incident", "Service status"], ["saved", "Saved"]];
function render(){document.documentElement.classList.toggle('dark',state.theme==='dark');$('theme').setAttribute('aria-label',t(state.theme==='dark'?'Switch to light theme':'Switch to dark theme'));$('views').replaceChildren(...views.map(([id,label])=>{const b=button(t(label),()=>{view=id;limit=25;render();});b.setAttribute('aria-current',String(view===id));if(id==='saved')b.append(el('span',number(state.saved.length)));return b;}));$('view-title').textContent=t(views.find(v=>v[0]===view)?.[1]||'All updates');const items=selected();$('count').textContent=t('{count} updates',{count:number(items.length)});
 $('items').replaceChildren(...items.slice(0,limit).map(item=>{const c=classify(item),card=el('article','','item'+(state.read.includes(item.id)?' read':'')),meta=el('div','','item-meta');meta.append(el('span',item.sourceId==='manual'?t("SAVED LINK"):t(c.category).toLocaleUpperCase(language),'category'),el('span',item.sourceId==='manual'?t('Your saved link'):item.sourceName),el('time',formatDate(item.publishedAt)));const h=el('h3');h.append(link(item.title,item.url));const summary=el('p',item.summary.slice(0,350)+(item.summary.length>350?'…':''),'summary'),reason=el('p',item.sourceId==='manual'?t("Saved by you. Not independently verified."):t(c.reason),'reason'),actions=el('div','','item-actions');const saved=state.saved.some(i=>i.id===item.id);const sb=button(saved?t("Saved ✓"):t("Save"),()=>{state.saved=saved?state.saved.filter(i=>i.id!==item.id):[item,...state.saved].slice(0,500);save();render();});sb.setAttribute('aria-pressed',String(saved));const rb=button(state.read.includes(item.id)?t("Mark unread"):t("Mark read"),()=>{state.read=state.read.includes(item.id)?state.read.filter(id=>id!==item.id):[...state.read,item.id];save();render();});actions.append(link(t("Read original ↗"),item.url),sb,rb);if(item.sourceId==='manual')actions.append(button(t("Remove"),()=>{state.manual=state.manual.filter(i=>i.id!==item.id);state.saved=state.saved.filter(i=>i.id!==item.id);save();render();}));card.append(meta,h,summary,reason,actions);return card;}));if(!items.length){const empty=el('div','','empty');empty.append(el('strong',busy?t("Tuning in…"):view==='saved'?t("A place for the useful ones."):t("Nothing to catch up on.")),el('p',busy?t("Checking the selected feeds."):query||unread?t("Try clearing the search or unread filter."):view==='reset'?t("No reset announcements matched the current feeds. Personal reminders are separate."):t("Check your sources, or come back after the next update.")));$('items').append(empty);}$('more').hidden=items.length<=limit;renderSources();}
function renderSources(){let enabled=0,healthy=0;$('source-list').replaceChildren(...sources.map(s=>{const off=state.disabled.includes(s.id),c=cache[s.id];if(!off){enabled++;if(c&&!c.error)healthy++;}const row=el('div','','source-row');row.append(el('span','','source-dot'+(off?' off':c?.error?' failed':'')),el('span',s.name));row.title=off?t("Muted"):c?.error&&t('Source unavailable')||c?.checkedAt&&t('Last checked {date}',{date:new Date(c.checkedAt).toLocaleString(language)})||t("Not checked yet");return row;}));$('source-count').textContent=t('{healthy} / {enabled} sources ready',{healthy:number(healthy),enabled:number(enabled)});$('freshness').textContent=busy?t("Checking for updates…"):Object.values(cache).some(c=>c.error)?t("Some sources need another try"):t("Checks every 15 min while visible");$('source-settings').replaceChildren(...sources.map(s=>{const row=el('div','','source-option'),label=el('label'),input=el('input');input.type='checkbox';input.checked=!state.disabled.includes(s.id);input.addEventListener('change',()=>{state.disabled=input.checked?state.disabled.filter(id=>id!==s.id):[...state.disabled,s.id];save();render();if(input.checked)void refresh();});label.append(input,document.createTextNode(' '+s.name));const c=cache[s.id];row.append(label,el('p',t(s.kind)+' · '+(c?.error?t('Source unavailable'):c?.checkedAt?t('Checked {date}',{date:new Date(c.checkedAt).toLocaleString(language)}):t("Not checked yet"))),link('RSS / Atom ↗',s.url));return row;}));}
async function notify(title:string,body:string,tag:string){if(!('Notification'in window)||Notification.permission!=='granted')return false;try{if('serviceWorker'in navigator){const reg=await readyWorker();await reg.showNotification(title,{body,tag,icon:'/icon.svg'});}else new Notification(title,{body,tag});return true;}catch{return false;}}
async function refresh(){if(busy)return;busy=true;($('refresh')as HTMLButtonElement).disabled=true;render();const known=new Set(state.seen),fresh:Item[]=[];await Promise.allSettled(sources.filter(s=>!state.disabled.includes(s.id)).map(async s=>{try{const r=await fetch(`/api/feed?source=${encodeURIComponent(s.id)}`,{signal:AbortSignal.timeout(12000)}),data=await r.json();if(!r.ok||data.error)throw Error(data.error||t("Source unavailable"));const items=data.items.filter(validItem);cache[s.id]={items,checkedAt:data.checkedAt};fresh.push(...items);for(const i of items)if(!state.seen.includes(i.id))state.seen.push(i.id);}catch(e){cache[s.id]={items:cache[s.id]?.items||[],checkedAt:cache[s.id]?.checkedAt||'',error:(e as Error).message};}}));const day=new Date().toLocaleDateString('en-CA');if(state.day!==day){state.day=day;state.sent=0;}if(initialized&&state.alerts&&!inQuietHours(new Date().getHours(),state.quietStart,state.quietEnd)&&state.sent<state.cap){const relevant=mergeItems(fresh).filter(i=>!known.has(i.id)&&classify(i).important&&Date.parse(i.publishedAt||'')>Date.now()-86400000);if(relevant.length&&await notify(t('{count} new important updates',{count:number(relevant.length)}),relevant[0].title,'quiet-signal-updates'))state.sent++;}initialized=true;busy=false;($('refresh')as HTMLButtonElement).disabled=false;save();render();const failed=sources.filter(s=>!state.disabled.includes(s.id)&&cache[s.id]?.error);$('notice').textContent=failed.length?t('{sources} unavailable. Any older items shown are cached. Details in Sources.',{sources:failed.map(s=>s.name).join(', ')}):'';}
$('refresh').addEventListener('click',()=>void refresh());$('theme').addEventListener('click',()=>{state.theme=state.theme==='dark'?'light':'dark';save();render();});$('search').addEventListener('input',e=>{query=(e.target as HTMLInputElement).value;limit=25;render();});$('unread').addEventListener('change',e=>{unread=(e.target as HTMLInputElement).checked;render();});$('more').addEventListener('click',()=>{limit+=25;render();});
for(const id of ['settings','sources','add','resets','about'])$(id+'-open').addEventListener('click',()=>{if(id==='resets')renderReminders();($(id)as HTMLDialogElement).showModal();});document.querySelectorAll<HTMLButtonElement>('[data-close]').forEach(b=>b.addEventListener('click',()=>($(b.dataset.close!)as HTMLDialogElement).close()));const mobile=el('div','','mobile-tools');$('feed').before(mobile);function renderMobile(){mobile.replaceChildren();for(const [id,label]of [['sources','Sources'],['add','Save link'],['resets','Reminders']])mobile.append(button(t(label),()=>{if(id==='resets')renderReminders();($(id)as HTMLDialogElement).showModal();}));mobile.append(link('Tibo ↗','https://x.com/thsottiaux'));}renderMobile();
$('link-form').addEventListener('submit',e=>{e.preventDefault();const url=safeUrl($<HTMLInputElement>('link-url').value);if(!url){$('link-status').textContent=t("Use a full HTTPS link without embedded credentials.");return;}const item:Item={id:'manual-'+crypto.randomUUID(),title:$<HTMLInputElement>('link-title').value.trim(),url,summary:$<HTMLTextAreaElement>('link-note').value.trim(),publishedAt:new Date().toISOString(),sourceId:'manual',sourceName:'Your saved link'};if(!item.title)return;state.manual=[item,...state.manual].slice(0,500);state.saved=[item,...state.saved].slice(0,500);save();view='saved';render();$<HTMLFormElement>('link-form').reset();$<HTMLDialogElement>('add').close();});
$('enable-notifications').addEventListener('click',async()=>{if(!('Notification'in window)){ $('notification-status').textContent=t("Notifications are not supported in this browser.");return;}const p=await Notification.requestPermission();$('notification-status').textContent=p==='granted'?t("Permission granted. Choose whether to enable in-app alerts below."):p==='denied'?t("Blocked by the browser. You can change this in site settings."):t("No permission granted.");});$('test-notification').addEventListener('click',async()=>{$('notification-status').textContent=await notify('Khonrelay',t("Your test notification. No feed item was marked as read."),'quiet-signal-test')?t("Test handed to your browser. OS settings may suppress its display."):t("Allow notifications first, or check browser support.");});
for(const id of ['quiet-start','quiet-end'])for(let h=0;h<24;h++){const o=el('option',String(h).padStart(2,'0')+':00');o.value=o.textContent!;$(id).append(o);}
$<HTMLInputElement>('alerts').checked=state.alerts;$<HTMLInputElement>('quiet-start').value=String(state.quietStart).padStart(2,'0')+':00';$<HTMLInputElement>('quiet-end').value=String(state.quietEnd).padStart(2,'0')+':00';$<HTMLSelectElement>('alert-cap').value=String(state.cap);$('timezone').textContent=t('Quiet hours use {zone}. Equal times disable quiet hours.',{zone:Intl.DateTimeFormat().resolvedOptions().timeZone});for(const id of ['alerts','quiet-start','quiet-end','alert-cap'])$(id).addEventListener('change',()=>{state.alerts=$<HTMLInputElement>('alerts').checked;state.quietStart=Number($<HTMLInputElement>('quiet-start').value.split(':')[0]);state.quietEnd=Number($<HTMLInputElement>('quiet-end').value.split(':')[0]);state.cap=Number($<HTMLSelectElement>('alert-cap').value);save();});
function renderReminders(){$('reminders').replaceChildren(...state.reminders.map(r=>{const n=el('div','','reminder');n.append(button(t("Remove"),()=>{state.reminders=state.reminders.filter(x=>x.id!==r.id);save();renderReminders();}),el('strong',r.name),el('span',new Date(r.at).toLocaleString(language)),el('p',Date.parse(r.at)<=Date.now()?t("Expected time reached. Check your provider to confirm."):t("Manual reminder. Not synced with an account.")));return n;}));}
$('reset-form').addEventListener('submit',e=>{e.preventDefault();const at=new Date($<HTMLInputElement>('reset-date').value);if(!Number.isFinite(at.getTime())||at.getTime()<Date.now()){const n=el('p',t("Choose a future time."));$('reminders').replaceChildren(n);return;}state.reminders.push({id:crypto.randomUUID(),name:$<HTMLInputElement>('reset-name').value.trim(),at:at.toISOString(),notified:false});state.reminders=state.reminders.slice(-20);save();renderReminders();$<HTMLFormElement>('reset-form').reset();});
function download(name:string,value:string,type:string){const u=URL.createObjectURL(new Blob([value],{type})),a=el('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),2000);}
$('export').addEventListener('click',()=>download('quiet-signal-backup.json',JSON.stringify(state,null,2),'application/json'));$('import').addEventListener('change',async()=>{try{const f=$<HTMLInputElement>('import').files?.[0];if(!f)return;if(f.size>3000000)throw Error(t("Maximum backup size is 3 MB."));const imported=parseState(JSON.parse(await f.text()));state.saved=mergeItems([...imported.saved,...state.saved]).slice(0,500);state.manual=mergeItems([...imported.manual,...state.manual]).slice(0,500);state.read=[...new Set([...state.read,...imported.read])];state.reminders=[...new Map([...state.reminders,...imported.reminders].map(r=>[r.id,r])).values()].slice(-20);save();render();$('backup-status').textContent=t("Saved links, read state and reminders merged. Current notification preferences are unchanged.");}catch(e){$('backup-status').textContent=errorText(e,'Choose a Khonrelay backup.');}});
const xml=(s:string)=>s.replace(/[<>&"']/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&apos;'}[c]!));$('opml').addEventListener('click',()=>download('quiet-signal-sources.opml',`<?xml version="1.0"?><opml version="2.0"><head><title>Khonrelay sources</title></head><body>${sources.filter(s=>!state.disabled.includes(s.id)).map(s=>`<outline text="${xml(s.name)}" title="${xml(s.name)}" type="rss" xmlUrl="${xml(s.url)}" htmlUrl="${xml(s.home)}"/>`).join('')}</body></opml>`,'text/xml'));
let workerRegistration:Promise<ServiceWorkerRegistration>|null=null;
if('serviceWorker'in navigator)workerRegistration=navigator.serviceWorker.register('/sw.js');
workerRegistration?.catch(()=>{$('notification-status').textContent=t("Service worker unavailable. Offline mode and some notifications may not work.");});
async function readyWorker(){if(!workerRegistration)throw Error(t("Service workers are unavailable."));let timer:ReturnType<typeof setTimeout>|undefined;try{return await Promise.race([workerRegistration.then(()=>navigator.serviceWorker.ready),new Promise<ServiceWorkerRegistration>((_,reject)=>{timer=setTimeout(()=>reject(Error(t("Notification setup timed out. Reload and try again."))),8000);})]);}finally{clearTimeout(timer);}}
setInterval(()=>{if(!document.hidden)void refresh();},15*60*1000);setInterval(()=>{for(const r of state.reminders){if(!r.notified&&Date.parse(r.at)<=Date.now()){r.notified=true;if(state.alerts&&!inQuietHours(new Date().getHours(),state.quietStart,state.quietEnd))void notify(r.name,t("Expected time reached. Check your provider to confirm."),'reminder-'+r.id);save();}}if($<HTMLDialogElement>('resets').open)renderReminders();},60000);
render();void refresh();
let hosted:{configured:boolean,publicKey:string|null}={configured:false,publicKey:null};
async function hostedStatus(){try{const r=await fetch('/api/push');hosted=await r.json();$('push-status').textContent=hosted.configured?t("Hosted service configured. Connect this device to receive a daily digest."):t("Not connected yet. Hosted push needs a free storage instance and deployment keys. In-app feeds already work.");for(const id of ['push-connect','push-test','push-disconnect'])$<HTMLButtonElement>(id).disabled=!hosted.configured;}catch{$('push-status').textContent=t("Could not check hosted notifications. Try again later.");}}
const pushPreferences=()=>({sources:sources.filter(s=>!state.disabled.includes(s.id)).map(s=>s.id),timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,quietStart:state.quietStart,quietEnd:state.quietEnd,priority:'important'});
async function pushRequest(body:object){const key=$<HTMLInputElement>('push-key').value;if(!key)throw Error(t("Enter your private enrollment key. It is not saved."));const r=await fetch('/api/push',{method:'POST',headers:{'Content-Type':'application/json','x-enrollment-key':key},body:JSON.stringify(body),signal:AbortSignal.timeout(15000)}),result=await r.json();if(!r.ok)throw Error(t('Could not update notifications.'));return result;}
for(const action of ['connect','test','disconnect'])$('push-'+action).addEventListener('click',async()=>{const b=$<HTMLButtonElement>('push-'+action);b.disabled=true;try{if(!('serviceWorker'in navigator)||!('PushManager'in window))throw Error(t("Web Push is not supported here. On iPhone, install this app to the Home Screen first."));if(!$<HTMLInputElement>('push-key').value)throw Error(t("Enter your private enrollment key first."));const reg=await readyWorker();let subscription=await reg.pushManager.getSubscription();if(action==='connect'){if(!hosted.publicKey)throw Error(t("Hosted push is not configured."));if(Notification.permission!=='granted'&&await Notification.requestPermission()!=='granted')throw Error(t("Notification permission was not granted."));let created=false;if(!subscription){const raw=atob(hosted.publicKey.replace(/-/g,'+').replace(/_/g,'/'));const key=Uint8Array.from(raw,c=>c.charCodeAt(0));subscription=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:key});created=true;}try{await pushRequest({action:'subscribe',subscription:subscription.toJSON(),preferences:pushPreferences()});}catch(e){if(created)await subscription.unsubscribe();throw e;}$('push-status').textContent=t("Connected. Daily digest enabled for this device. No old-post backlog will be sent.");}else if(action==='test'){if(!subscription)throw Error(t("Connect this device first."));await pushRequest({action:'test',subscription:subscription.toJSON()});$('push-status').textContent=t("Test sent through the hosted service. Check your device notifications.");}else{if(!subscription)throw Error(t("This browser has no push subscription."));await pushRequest({action:'unsubscribe',endpoint:subscription.endpoint});await subscription.unsubscribe();$('push-status').textContent=t("Disconnected. Server subscription deleted.");}}catch(e){$('push-status').textContent=errorText(e,'Could not update notifications.');}finally{b.disabled=!hosted.configured;}});
void hostedStatus();

const languageSelect=$<HTMLSelectElement>('language');for(const [code,name] of Object.entries(languages)){const option=el('option',name);option.value=code;languageSelect.append(option);}languageSelect.value=language;translateStatic();languageSelect.addEventListener('change',()=>{for(const id of ['notice','notification-status','backup-status','link-status','push-status']){const node=$(id);node.dataset.statusKey=Object.keys(catalog).find(key=>t(key)===node.textContent)||'';}setLanguage(languageSelect.value);translateStatic();render();renderMobile();renderReminders();$('timezone').textContent=t('Quiet hours use {zone}. Equal times disable quiet hours.',{zone:Intl.DateTimeFormat().resolvedOptions().timeZone});for(const id of ['notice','notification-status','backup-status','link-status','push-status']){const node=$(id);if(node.dataset.statusKey)node.textContent=t(node.dataset.statusKey);}const failed=sources.filter(s=>!state.disabled.includes(s.id)&&cache[s.id]?.error);if(failed.length)$('notice').textContent=t('{sources} unavailable. Any older items shown are cached. Details in Sources.',{sources:failed.map(s=>s.name).join(', ')});});

$('relevance').addEventListener('change',e=>{relevanceEnabled=(e.target as HTMLInputElement).checked;limit=25;render();});
void fetch('/relevance.json',{signal:AbortSignal.timeout(6000)}).then(async r=>{if(!r.ok)return;const data=await r.json();const age=Date.now()-Date.parse(data.generatedAt);if(data.version===1&&Array.isArray(data.items)&&data.items.length&&Number.isFinite(age)&&age>=-60000&&age<=7*86400000){relevanceSnapshot=data;$<HTMLInputElement>('relevance').disabled=false;}}).catch(()=>{});
